// src/ide/nvidia/jetsonTemplates.ts
// ═══════════════════════════════════════════════════════════════
// 🟢 JETSON PROJECT TEMPLATES — Phase 1: Jetson Aware  
// ═══════════════════════════════════════════════════════════════
// Adds Jetson/CUDA project scaffolding to the existing project
// creation system. RAM Impact: 0KB (templates are disk-only,
// copied when user creates a project).

export interface JetsonTemplate {
  id: string;
  name: string;
  description: string;
  category: 'jetson' | 'cuda' | 'tensorrt';
  icon: string;
  files: Record<string, string>;
}

// ════════════════════════════════════════════
// TEMPLATE DEFINITIONS
// ════════════════════════════════════════════

export const JETSON_TEMPLATES: JetsonTemplate[] = [
  // ── 1. CUDA Basic Kernel ──
  {
    id: 'cuda-basic',
    name: 'CUDA Basic Kernel',
    description: 'Simple CUDA kernel with memory management, error checking, and benchmarking',
    category: 'cuda',
    icon: '🟢',
    files: {
      'main.cu': `// CUDA Basic Kernel — Generated by Operator X02
#include <stdio.h>
#include <cuda_runtime.h>

// Error checking macro
#define CUDA_CHECK(call) do { \\
    cudaError_t err = call; \\
    if (err != cudaSuccess) { \\
        fprintf(stderr, "CUDA error at %s:%d: %s\\n", \\
                __FILE__, __LINE__, cudaGetErrorString(err)); \\
        exit(EXIT_FAILURE); \\
    } \\
} while(0)

// Simple vector addition kernel
__global__ void vectorAdd(const float* a, const float* b, float* c, int n) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < n) {
        c[idx] = a[idx] + b[idx];
    }
}

int main() {
    const int N = 1 << 20;  // 1M elements
    const size_t bytes = N * sizeof(float);

    // Host memory
    float *h_a, *h_b, *h_c;
    h_a = (float*)malloc(bytes);
    h_b = (float*)malloc(bytes);
    h_c = (float*)malloc(bytes);

    // Initialize
    for (int i = 0; i < N; i++) {
        h_a[i] = (float)i;
        h_b[i] = (float)(i * 2);
    }

    // Device memory
    float *d_a, *d_b, *d_c;
    CUDA_CHECK(cudaMalloc(&d_a, bytes));
    CUDA_CHECK(cudaMalloc(&d_b, bytes));
    CUDA_CHECK(cudaMalloc(&d_c, bytes));

    // Copy to device
    CUDA_CHECK(cudaMemcpy(d_a, h_a, bytes, cudaMemcpyHostToDevice));
    CUDA_CHECK(cudaMemcpy(d_b, h_b, bytes, cudaMemcpyHostToDevice));

    // Launch kernel
    int blockSize = 256;
    int numBlocks = (N + blockSize - 1) / blockSize;
    
    // Benchmark
    cudaEvent_t start, stop;
    cudaEventCreate(&start);
    cudaEventCreate(&stop);
    cudaEventRecord(start);

    vectorAdd<<<numBlocks, blockSize>>>(d_a, d_b, d_c, N);

    cudaEventRecord(stop);
    cudaEventSynchronize(stop);
    
    float ms = 0;
    cudaEventElapsedTime(&ms, start, stop);

    // Copy result back
    CUDA_CHECK(cudaMemcpy(h_c, d_c, bytes, cudaMemcpyDeviceToHost));

    // Verify
    bool passed = true;
    for (int i = 0; i < N; i++) {
        if (h_c[i] != h_a[i] + h_b[i]) {
            printf("Mismatch at %d: expected %f, got %f\\n", i, h_a[i] + h_b[i], h_c[i]);
            passed = false;
            break;
        }
    }

    printf("Vector Add (%d elements): %s in %.3f ms\\n", N, passed ? "PASSED" : "FAILED", ms);

    // Cleanup
    cudaFree(d_a); cudaFree(d_b); cudaFree(d_c);
    free(h_a); free(h_b); free(h_c);
    cudaEventDestroy(start); cudaEventDestroy(stop);

    return passed ? 0 : 1;
}
`,
      'Makefile': `# CUDA Basic Kernel — Makefile
# Generated by Operator X02

NVCC = nvcc
NVCC_FLAGS = -O2 -arch=sm_72  # sm_72 for Jetson Xavier/Orin
TARGET = vectoradd

all: $(TARGET)

$(TARGET): main.cu
\t$(NVCC) $(NVCC_FLAGS) -o $@ $<

run: $(TARGET)
\t./$(TARGET)

clean:
\trm -f $(TARGET)

# For Jetson Orin Nano: use -arch=sm_87
# For Jetson Xavier NX: use -arch=sm_72
# For Desktop GPUs:     use -arch=sm_86 (RTX 30xx) or sm_89 (RTX 40xx)
jetson-orin: main.cu
\t$(NVCC) -O2 -arch=sm_87 -o $(TARGET) $<

.PHONY: all run clean jetson-orin
`,
      'README.md': `# CUDA Basic Kernel

Generated by **Operator X02 IDE** 🟢

## Build & Run

\`\`\`bash
# Desktop (adjust -arch for your GPU)
make && make run

# Jetson Orin Nano
make jetson-orin && make run
\`\`\`

## Compute Capabilities
| Device | Architecture |
|--------|-------------|
| Jetson Orin Nano/NX | sm_87 |
| Jetson Xavier NX | sm_72 |
| RTX 3060-3090 | sm_86 |
| RTX 4060-4090 | sm_89 |
`,
    },
  },

  // ── 2. Jetson Python AI Inference ──
  {
    id: 'jetson-python',
    name: 'Jetson Python AI Inference',
    description: 'Python inference starter with PyTorch/TensorRT on Jetson, camera capture, and power monitoring',
    category: 'jetson',
    icon: '🤖',
    files: {
      'inference.py': `#!/usr/bin/env python3
"""
Jetson AI Inference Starter — Generated by Operator X02
Supports: PyTorch, TensorRT, ONNX Runtime on NVIDIA Jetson
"""
import time
import numpy as np

# ── Check available backends ──
BACKENDS = {}

try:
    import torch
    BACKENDS['pytorch'] = True
    print(f"✅ PyTorch {torch.__version__} (CUDA: {torch.cuda.is_available()})")
except ImportError:
    BACKENDS['pytorch'] = False
    print("ℹ️  PyTorch not installed")

try:
    import tensorrt as trt
    BACKENDS['tensorrt'] = True
    print(f"✅ TensorRT {trt.__version__}")
except ImportError:
    BACKENDS['tensorrt'] = False
    print("ℹ️  TensorRT not installed")

try:
    import onnxruntime as ort
    BACKENDS['onnxruntime'] = True
    providers = ort.get_available_providers()
    print(f"✅ ONNX Runtime {ort.__version__} (Providers: {providers})")
except ImportError:
    BACKENDS['onnxruntime'] = False
    print("ℹ️  ONNX Runtime not installed")


def get_jetson_info() -> dict:
    """Read Jetson device info from /etc/nv_tegra_release or tegrastats"""
    info = {"model": "Unknown", "jetpack": "Unknown", "cuda_cores": 0}
    try:
        with open("/etc/nv_tegra_release", "r") as f:
            info["release"] = f.readline().strip()
    except FileNotFoundError:
        pass
    
    try:
        import subprocess
        result = subprocess.run(["cat", "/proc/device-tree/model"], 
                              capture_output=True, text=True, timeout=5)
        if result.returncode == 0:
            info["model"] = result.stdout.strip().replace("\\x00", "")
    except Exception:
        pass
    
    return info


def pytorch_inference_example():
    """Simple PyTorch inference benchmark"""
    if not BACKENDS.get('pytorch') or not torch.cuda.is_available():
        print("⚠️  PyTorch CUDA not available, skipping")
        return
    
    device = torch.device("cuda")
    print(f"\\n🔥 PyTorch on: {torch.cuda.get_device_name(0)}")
    
    # Create a simple model (replace with your own)
    model = torch.nn.Sequential(
        torch.nn.Linear(784, 256),
        torch.nn.ReLU(),
        torch.nn.Linear(256, 10),
    ).to(device)
    model.eval()
    
    # Benchmark
    dummy_input = torch.randn(1, 784, device=device)
    
    # Warmup
    for _ in range(10):
        with torch.no_grad():
            _ = model(dummy_input)
    torch.cuda.synchronize()
    
    # Measure
    start = time.perf_counter()
    iterations = 1000
    for _ in range(iterations):
        with torch.no_grad():
            _ = model(dummy_input)
    torch.cuda.synchronize()
    elapsed = time.perf_counter() - start
    
    fps = iterations / elapsed
    latency_ms = (elapsed / iterations) * 1000
    print(f"📊 {iterations} inferences in {elapsed:.3f}s")
    print(f"   Throughput: {fps:.1f} FPS")
    print(f"   Latency:   {latency_ms:.2f} ms/inference")


def monitor_power():
    """Read Jetson power consumption (Orin/Xavier)"""
    try:
        import subprocess
        result = subprocess.run(
            ["cat", "/sys/bus/i2c/drivers/ina3221/1-0040/hwmon/hwmon1/in1_input"],
            capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            voltage_mv = int(result.stdout.strip())
            print(f"⚡ Board voltage: {voltage_mv}mV")
    except Exception:
        print("ℹ️  Power monitoring not available (desktop GPU?)")


if __name__ == "__main__":
    print("=" * 50)
    print("🤖 Jetson AI Inference — Operator X02")
    print("=" * 50)
    
    # Show device info
    info = get_jetson_info()
    print(f"Device: {info['model']}")
    
    # Run PyTorch benchmark
    pytorch_inference_example()
    
    # Check power
    monitor_power()
    
    print("\\n✅ Done! Edit this file to load your own model.")
`,
      'requirements.txt': `# Jetson Python AI Inference — Dependencies
# Generated by Operator X02
# 
# Note: On Jetson, install PyTorch from NVIDIA's wheel:
#   pip3 install torch --index-url https://developer.download.nvidia.com/compute/redist/jp/v60/
#
# For TensorRT, it comes pre-installed with JetPack SDK.

numpy>=1.21.0
opencv-python>=4.5.0
Pillow>=9.0.0
# torch       # Install from NVIDIA wheel (see above)
# tensorrt    # Comes with JetPack SDK
# onnxruntime-gpu  # Optional: pip3 install onnxruntime-gpu
`,
      'camera_capture.py': `#!/usr/bin/env python3
"""
Jetson Camera Capture — GStreamer pipeline for CSI/USB cameras
Generated by Operator X02
"""
import cv2
import time


def gstreamer_pipeline(
    sensor_id=0,
    capture_width=1280,
    capture_height=720,
    display_width=640,
    display_height=480,
    framerate=30,
    flip_method=0,
):
    """Build GStreamer pipeline string for Jetson CSI camera"""
    return (
        f"nvarguscamerasrc sensor-id={sensor_id} ! "
        f"video/x-raw(memory:NVMM), width=(int){capture_width}, "
        f"height=(int){capture_height}, framerate=(fraction){framerate}/1 ! "
        f"nvvidconv flip-method={flip_method} ! "
        f"video/x-raw, width=(int){display_width}, height=(int){display_height}, "
        f"format=(string)BGRx ! videoconvert ! "
        f"video/x-raw, format=(string)BGR ! appsink"
    )


def usb_camera(device=0, width=640, height=480):
    """Simple USB camera capture"""
    return cv2.VideoCapture(device)


if __name__ == "__main__":
    print("🎥 Jetson Camera Capture — Operator X02")
    print("Trying USB camera first, then CSI...")
    
    # Try USB first (works everywhere)
    cap = usb_camera()
    if not cap.isOpened():
        # Try CSI pipeline (Jetson only)
        pipeline = gstreamer_pipeline()
        cap = cv2.VideoCapture(pipeline, cv2.CAP_GSTREAMER)
    
    if not cap.isOpened():
        print("❌ No camera found. Connect a USB or CSI camera.")
        exit(1)
    
    print("✅ Camera opened! Press 'q' to quit, 's' to save frame.")
    
    frame_count = 0
    start_time = time.time()
    
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        
        frame_count += 1
        elapsed = time.time() - start_time
        fps = frame_count / elapsed if elapsed > 0 else 0
        
        # Draw FPS on frame
        cv2.putText(frame, f"FPS: {fps:.1f}", (10, 30),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
        
        cv2.imshow("Jetson Camera — Operator X02", frame)
        
        key = cv2.waitKey(1) & 0xFF
        if key == ord('q'):
            break
        elif key == ord('s'):
            filename = f"capture_{frame_count}.jpg"
            cv2.imwrite(filename, frame)
            print(f"📸 Saved {filename}")
    
    cap.release()
    cv2.destroyAllWindows()
    print(f"Captured {frame_count} frames at {fps:.1f} FPS average")
`,
      'README.md': `# Jetson Python AI Inference

Generated by **Operator X02 IDE** 🤖

## Quick Start

\`\`\`bash
# Install dependencies
pip3 install -r requirements.txt

# Run inference benchmark
python3 inference.py

# Test camera
python3 camera_capture.py
\`\`\`

## Jetson Setup
1. Flash JetPack 6.x via SDK Manager
2. PyTorch: Install from NVIDIA wheel (see requirements.txt)
3. TensorRT: Comes pre-installed with JetPack

## Power Modes (Orin Nano)
\`\`\`bash
sudo nvpmodel -m 0   # MAXN (15W) — maximum performance
sudo nvpmodel -m 1   # 15W
sudo nvpmodel -m 2   # 7W — power saving
sudo jetson_clocks    # Lock at max frequency
\`\`\`
`,
    },
  },

  // ── 3. TensorRT Optimization Pipeline ──
  {
    id: 'jetson-tensorrt',
    name: 'Jetson TensorRT Pipeline',
    description: 'Convert ONNX models to TensorRT for optimized inference on Jetson',
    category: 'tensorrt',
    icon: '⚡',
    files: {
      'convert_to_trt.py': `#!/usr/bin/env python3
"""
TensorRT Model Conversion — Generated by Operator X02
Convert ONNX model to TensorRT engine for Jetson deployment
"""
import os
import time

try:
    import tensorrt as trt
except ImportError:
    print("❌ TensorRT not installed. On Jetson, it comes with JetPack SDK.")
    print("   On desktop: pip install tensorrt")
    exit(1)


TRT_LOGGER = trt.Logger(trt.Logger.INFO)


def build_engine(onnx_path: str, engine_path: str, 
                 fp16: bool = True, int8: bool = False,
                 max_batch_size: int = 1,
                 workspace_mb: int = 1024):
    """Convert ONNX model to TensorRT engine"""
    
    print(f"🔧 Converting: {onnx_path}")
    print(f"   FP16: {fp16}, INT8: {int8}, Max Batch: {max_batch_size}")
    
    builder = trt.Builder(TRT_LOGGER)
    network = builder.create_network(
        1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    )
    parser = trt.OnnxParser(network, TRT_LOGGER)
    
    # Parse ONNX
    with open(onnx_path, "rb") as f:
        if not parser.parse(f.read()):
            for i in range(parser.num_errors):
                print(f"  ❌ {parser.get_error(i)}")
            return False
    
    print(f"   Network: {network.num_layers} layers, "
          f"{network.num_inputs} inputs, {network.num_outputs} outputs")
    
    # Build config
    config = builder.create_builder_config()
    config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, workspace_mb * (1 << 20))
    
    if fp16 and builder.platform_has_fast_fp16:
        config.set_flag(trt.BuilderFlag.FP16)
        print("   ✅ FP16 enabled")
    
    if int8 and builder.platform_has_fast_int8:
        config.set_flag(trt.BuilderFlag.INT8)
        print("   ✅ INT8 enabled (requires calibration data)")
    
    # Build engine
    print("   ⏳ Building engine (this may take several minutes on Jetson)...")
    start = time.time()
    engine = builder.build_serialized_network(network, config)
    elapsed = time.time() - start
    
    if engine is None:
        print("   ❌ Engine build failed")
        return False
    
    # Save
    with open(engine_path, "wb") as f:
        f.write(engine)
    
    size_mb = os.path.getsize(engine_path) / (1024 * 1024)
    print(f"   ✅ Saved: {engine_path} ({size_mb:.1f} MB) in {elapsed:.1f}s")
    return True


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="ONNX to TensorRT converter")
    parser.add_argument("onnx", help="Input ONNX model path")
    parser.add_argument("-o", "--output", help="Output engine path")
    parser.add_argument("--fp16", action="store_true", default=True, help="Enable FP16")
    parser.add_argument("--int8", action="store_true", help="Enable INT8")
    parser.add_argument("--workspace", type=int, default=1024, help="Workspace MB")
    
    args = parser.parse_args()
    output = args.output or args.onnx.replace(".onnx", ".engine")
    
    print("⚡ TensorRT Converter — Operator X02")
    success = build_engine(args.onnx, output, args.fp16, args.int8, 
                          workspace_mb=args.workspace)
    
    if success:
        print("\\n✅ Conversion complete! Deploy the .engine file to your Jetson.")
    else:
        print("\\n❌ Conversion failed. Check the ONNX model compatibility.")
`,
      'run_trt_inference.py': `#!/usr/bin/env python3
"""
TensorRT Inference Runner — Generated by Operator X02
Load and run a TensorRT engine on Jetson
"""
import time
import numpy as np

try:
    import tensorrt as trt
    import pycuda.driver as cuda
    import pycuda.autoinit
except ImportError as e:
    print(f"❌ Missing dependency: {e}")
    print("   Install: pip3 install pycuda")
    exit(1)


TRT_LOGGER = trt.Logger(trt.Logger.WARNING)


def load_engine(engine_path: str):
    """Load serialized TensorRT engine"""
    runtime = trt.Runtime(TRT_LOGGER)
    with open(engine_path, "rb") as f:
        return runtime.deserialize_cuda_engine(f.read())


def run_inference(engine_path: str, iterations: int = 100):
    """Run TensorRT inference benchmark"""
    print(f"Loading engine: {engine_path}")
    engine = load_engine(engine_path)
    context = engine.create_execution_context()
    
    # Allocate buffers
    inputs, outputs, bindings = [], [], []
    stream = cuda.Stream()
    
    for i in range(engine.num_io_tensors):
        name = engine.get_tensor_name(i)
        shape = engine.get_tensor_shape(name)
        dtype = trt.nptype(engine.get_tensor_dtype(name))
        size = np.prod(shape)
        
        host_mem = cuda.pagelocked_empty(int(size), dtype)
        device_mem = cuda.mem_alloc(host_mem.nbytes)
        bindings.append(int(device_mem))
        
        mode = engine.get_tensor_mode(name)
        if mode == trt.TensorIOMode.INPUT:
            inputs.append({"host": host_mem, "device": device_mem, "name": name, "shape": shape})
            np.copyto(host_mem, np.random.random(int(size)).astype(dtype))
        else:
            outputs.append({"host": host_mem, "device": device_mem, "name": name, "shape": shape})
    
    print(f"Inputs:  {[(i['name'], i['shape']) for i in inputs]}")
    print(f"Outputs: {[(o['name'], o['shape']) for o in outputs]}")
    
    # Warmup
    for _ in range(10):
        for inp in inputs:
            cuda.memcpy_htod_async(inp["device"], inp["host"], stream)
        context.execute_async_v2(bindings, stream.handle)
        for out in outputs:
            cuda.memcpy_dtoh_async(out["host"], out["device"], stream)
        stream.synchronize()
    
    # Benchmark
    start = time.perf_counter()
    for _ in range(iterations):
        for inp in inputs:
            cuda.memcpy_htod_async(inp["device"], inp["host"], stream)
        context.execute_async_v2(bindings, stream.handle)
        for out in outputs:
            cuda.memcpy_dtoh_async(out["host"], out["device"], stream)
        stream.synchronize()
    elapsed = time.perf_counter() - start
    
    fps = iterations / elapsed
    latency = (elapsed / iterations) * 1000
    
    print(f"\\n📊 TensorRT Benchmark ({iterations} iterations):")
    print(f"   Throughput: {fps:.1f} FPS")
    print(f"   Latency:   {latency:.2f} ms/inference")
    print(f"   Total:     {elapsed:.3f}s")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("engine", help="TensorRT engine file (.engine)")
    parser.add_argument("-n", type=int, default=100, help="Iterations")
    args = parser.parse_args()
    
    print("⚡ TensorRT Inference — Operator X02")
    run_inference(args.engine, args.n)
`,
      'README.md': `# Jetson TensorRT Pipeline

Generated by **Operator X02 IDE** ⚡

## Workflow

1. **Export** your model to ONNX (from PyTorch, TensorFlow, etc.)
2. **Convert** to TensorRT engine:
   \`\`\`bash
   python3 convert_to_trt.py model.onnx --fp16
   \`\`\`
3. **Run** optimized inference:
   \`\`\`bash
   python3 run_trt_inference.py model.engine -n 1000
   \`\`\`

## Performance Tips
- Use FP16 on Jetson Orin (default) — 2x faster, minimal accuracy loss
- INT8 gives another 2x but requires calibration dataset
- Set power mode: \`sudo nvpmodel -m 0 && sudo jetson_clocks\`
`,
    },
  },
];

// ════════════════════════════════════════════
// TEMPLATE REGISTRATION
// ════════════════════════════════════════════

/**
 * Get all Jetson/CUDA templates for the project creation dialog
 */
export function getJetsonTemplates(): JetsonTemplate[] {
  return JETSON_TEMPLATES;
}

/**
 * Get template by ID
 */
export function getJetsonTemplateById(id: string): JetsonTemplate | undefined {
  return JETSON_TEMPLATES.find(t => t.id === id);
}

/**
 * Create project files from a Jetson template
 * Returns array of { path, content } for the file creation system
 */
export function createJetsonProjectFiles(templateId: string): Array<{ path: string; content: string }> {
  const template = getJetsonTemplateById(templateId);
  if (!template) {
    console.error(`❌ [JETSON] Template not found: ${templateId}`);
    return [];
  }
  
  return Object.entries(template.files).map(([path, content]) => ({
    path,
    content,
  }));
}

/**
 * Get template categories for UI grouping
 */
export function getJetsonTemplateCategories(): Array<{ id: string; name: string; icon: string }> {
  return [
    { id: 'cuda', name: 'CUDA', icon: '🟢' },
    { id: 'jetson', name: 'Jetson', icon: '🤖' },
    { id: 'tensorrt', name: 'TensorRT', icon: '⚡' },
  ];
}

console.log(`🟢 [JETSON] ${JETSON_TEMPLATES.length} project templates loaded`);
