// ============================================================================
// 🎮 PHASER GAME TEMPLATES - Operator X02 Code IDE
// ============================================================================
// Ready-to-use game templates for Phaser 3
// ============================================================================

// ============================================================================
// PLATFORMER TEMPLATE - GameScene
// ============================================================================

export const PLATFORMER_GAME_SCENE = `// ============================================================================
// 🏃 PLATFORMER GAME SCENE
// ============================================================================
// Generated by Operator X02 Code IDE
// ============================================================================

export class GameScene extends Phaser.Scene {
  // Player
  private player!: Phaser.Physics.Arcade.Sprite;
  private cursors!: Phaser.Types.Input.Keyboard.CursorKeys;
  
  // World
  private platforms!: Phaser.Physics.Arcade.StaticGroup;
  private coins!: Phaser.Physics.Arcade.Group;
  private enemies!: Phaser.Physics.Arcade.Group;
  
  // State
  private score: number = 0;
  private lives: number = 3;
  private isInvincible: boolean = false;
  
  // UI
  private scoreText!: Phaser.GameObjects.Text;
  private livesText!: Phaser.GameObjects.Text;

  constructor() {
    super({ key: 'GameScene' });
  }

  create(): void {
    const { width, height } = this.cameras.main;

    // Background gradient
    const bg = this.add.graphics();
    bg.fillGradientStyle(0x87CEEB, 0x87CEEB, 0x98FB98, 0x98FB98);
    bg.fillRect(0, 0, width, height);

    // Create platforms
    this.createPlatforms();
    
    // Create player
    this.createPlayer();
    
    // Create collectibles
    this.createCoins();
    
    // Create enemies
    this.createEnemies();
    
    // Setup collisions
    this.setupCollisions();
    
    // Setup input
    this.cursors = this.input.keyboard!.createCursorKeys();
    
    // UI
    this.createUI();

    console.log('🎮 Platformer GameScene started!');
  }

  private createPlatforms(): void {
    const { width, height } = this.cameras.main;
    
    this.platforms = this.physics.add.staticGroup();
    
    // Ground
    const ground = this.add.rectangle(width / 2, height - 20, width, 40, 0x8B4513);
    this.platforms.add(ground);
    
    // Floating platforms
    const platformData = [
      { x: 150, y: height - 150, w: 200 },
      { x: 450, y: height - 250, w: 150 },
      { x: 700, y: height - 150, w: 200 },
      { x: 300, y: height - 400, w: 180 },
      { x: 600, y: height - 350, w: 150 }
    ];
    
    platformData.forEach(p => {
      const platform = this.add.rectangle(p.x, p.y, p.w, 20, 0x654321);
      this.platforms.add(platform);
    });
  }

  private createPlayer(): void {
    const { height } = this.cameras.main;
    
    // Create player graphics
    const graphics = this.add.graphics();
    graphics.fillStyle(0x00ff88);
    graphics.fillRect(0, 0, 32, 48);
    graphics.generateTexture('player', 32, 48);
    graphics.destroy();
    
    this.player = this.physics.add.sprite(100, height - 100, 'player');
    this.player.setCollideWorldBounds(true);
    this.player.setBounce(0.1);
  }

  private createCoins(): void {
    this.coins = this.physics.add.group();
    
    const coinPositions = [
      { x: 150, y: 200 }, { x: 250, y: 200 },
      { x: 450, y: 150 }, { x: 550, y: 150 },
      { x: 700, y: 200 }, { x: 300, y: 300 },
      { x: 600, y: 250 }
    ];
    
    coinPositions.forEach(pos => {
      const coin = this.add.circle(pos.x, pos.y, 12, 0xFFD700);
      this.coins.add(coin);
      (coin.body as Phaser.Physics.Arcade.Body).setAllowGravity(false);
      
      // Floating animation
      this.tweens.add({
        targets: coin,
        y: pos.y - 10,
        duration: 1000,
        yoyo: true,
        repeat: -1,
        ease: 'Sine.easeInOut'
      });
    });
  }

  private createEnemies(): void {
    this.enemies = this.physics.add.group();
    
    const enemyPositions = [
      { x: 300, y: 500, patrol: { min: 200, max: 400 } },
      { x: 600, y: 350, patrol: { min: 500, max: 700 } }
    ];
    
    enemyPositions.forEach(pos => {
      const enemy = this.add.circle(pos.x, pos.y, 20, 0xFF4444);
      this.enemies.add(enemy);
      (enemy.body as Phaser.Physics.Arcade.Body).setAllowGravity(false);
      
      // Patrol movement
      this.tweens.add({
        targets: enemy,
        x: pos.patrol.max,
        duration: 2000,
        yoyo: true,
        repeat: -1,
        ease: 'Linear'
      });
    });
  }

  private setupCollisions(): void {
    // Player collides with platforms
    this.physics.add.collider(this.player, this.platforms);
    
    // Collect coins
    this.physics.add.overlap(
      this.player, 
      this.coins, 
      this.collectCoin as any, 
      undefined, 
      this
    );
    
    // Enemy collision
    this.physics.add.overlap(
      this.player,
      this.enemies,
      this.hitEnemy as any,
      undefined,
      this
    );
  }

  private createUI(): void {
    this.scoreText = this.add.text(16, 16, 'Score: 0', {
      font: 'bold 24px Arial',
      color: '#000000'
    }).setScrollFactor(0);
    
    this.livesText = this.add.text(16, 50, '❤️❤️❤️', {
      font: '24px Arial'
    }).setScrollFactor(0);
  }

  private collectCoin(player: any, coin: any): void {
    coin.destroy();
    this.score += 10;
    this.scoreText.setText(\`Score: \${this.score}\`);
    
    // Check if all coins collected
    if (this.coins.countActive() === 0) {
      this.createCoins();
    }
  }

  private hitEnemy(player: any, enemy: any): void {
    if (this.isInvincible) return;
    
    // Check if stomping
    const playerBody = player.body as Phaser.Physics.Arcade.Body;
    const enemyBody = enemy.body as Phaser.Physics.Arcade.Body;
    
    if (playerBody.velocity.y > 0 && player.y < enemy.y - 10) {
      // Stomp enemy
      enemy.destroy();
      playerBody.setVelocityY(-300);
      this.score += 50;
      this.scoreText.setText(\`Score: \${this.score}\`);
    } else {
      // Take damage
      this.takeDamage();
    }
  }

  private takeDamage(): void {
    this.lives--;
    this.livesText.setText('❤️'.repeat(this.lives));
    
    if (this.lives <= 0) {
      this.scene.start('GameOverScene', { score: this.score });
      return;
    }
    
    // Invincibility frames
    this.isInvincible = true;
    this.player.setTint(0xff0000);
    
    this.time.delayedCall(1500, () => {
      this.isInvincible = false;
      this.player.clearTint();
    });
  }

  update(): void {
    const body = this.player.body as Phaser.Physics.Arcade.Body;
    
    // Horizontal movement
    if (this.cursors.left.isDown) {
      body.setVelocityX(-200);
      this.player.setFlipX(true);
    } else if (this.cursors.right.isDown) {
      body.setVelocityX(200);
      this.player.setFlipX(false);
    } else {
      body.setVelocityX(0);
    }
    
    // Jumping
    if (this.cursors.up.isDown && body.onFloor()) {
      body.setVelocityY(-450);
    }
    
    // Fall death
    if (this.player.y > this.cameras.main.height + 50) {
      this.takeDamage();
      this.player.setPosition(100, 100);
      body.setVelocity(0);
    }
  }
}
`;

// ============================================================================
// SHOOTER TEMPLATE - GameScene
// ============================================================================

export const SHOOTER_GAME_SCENE = `// ============================================================================
// 🚀 SPACE SHOOTER GAME SCENE
// ============================================================================
// Generated by Operator X02 Code IDE
// ============================================================================

export class GameScene extends Phaser.Scene {
  // Player
  private player!: Phaser.GameObjects.Triangle;
  
  // Groups
  private bullets!: Phaser.GameObjects.Group;
  private enemies!: Phaser.GameObjects.Group;
  private powerups!: Phaser.GameObjects.Group;
  private particles!: Phaser.GameObjects.Group;
  
  // Input
  private cursors!: Phaser.Types.Input.Keyboard.CursorKeys;
  private spaceKey!: Phaser.Input.Keyboard.Key;
  
  // State
  private score: number = 0;
  private lives: number = 3;
  private level: number = 1;
  private lastShot: number = 0;
  private lastSpawn: number = 0;
  private rapidFire: boolean = false;
  private shield: boolean = false;
  
  // UI
  private scoreText!: Phaser.GameObjects.Text;
  private livesText!: Phaser.GameObjects.Text;
  private levelText!: Phaser.GameObjects.Text;

  constructor() {
    super({ key: 'GameScene' });
  }

  create(): void {
    const { width, height } = this.cameras.main;

    // Starfield background
    this.createStarfield();
    
    // Create player
    this.createPlayer();
    
    // Initialize groups
    this.bullets = this.add.group();
    this.enemies = this.add.group();
    this.powerups = this.add.group();
    this.particles = this.add.group();
    
    // Input
    this.cursors = this.input.keyboard!.createCursorKeys();
    this.spaceKey = this.input.keyboard!.addKey(Phaser.Input.Keyboard.KeyCodes.SPACE);
    
    // UI
    this.createUI();

    console.log('🎮 Space Shooter GameScene started!');
  }

  private createStarfield(): void {
    const { width, height } = this.cameras.main;
    
    for (let i = 0; i < 100; i++) {
      const star = this.add.circle(
        Math.random() * width,
        Math.random() * height,
        Math.random() * 2 + 0.5,
        0xffffff,
        Math.random() * 0.5 + 0.3
      );
      
      this.tweens.add({
        targets: star,
        y: height + 10,
        duration: Math.random() * 3000 + 2000,
        repeat: -1,
        onRepeat: () => {
          star.y = -10;
          star.x = Math.random() * width;
        }
      });
    }
  }

  private createPlayer(): void {
    const { width, height } = this.cameras.main;
    
    this.player = this.add.triangle(
      width / 2, height - 60,
      0, 30, 20, 0, 40, 30,
      0x00ff88
    );
    
    this.physics.add.existing(this.player);
    (this.player.body as Phaser.Physics.Arcade.Body).setCollideWorldBounds(true);
  }

  private createUI(): void {
    const { width } = this.cameras.main;
    
    this.scoreText = this.add.text(16, 16, 'Score: 0', {
      font: 'bold 24px Arial',
      color: '#00ff88'
    });
    
    this.levelText = this.add.text(width / 2, 16, 'Level: 1', {
      font: 'bold 20px Arial',
      color: '#4dabf7'
    }).setOrigin(0.5, 0);
    
    this.livesText = this.add.text(width - 16, 16, '❤️❤️❤️', {
      font: '24px Arial'
    }).setOrigin(1, 0);
  }

  private shoot(): void {
    const now = this.time.now;
    const cooldown = this.rapidFire ? 100 : 200;
    
    if (now - this.lastShot < cooldown) return;
    this.lastShot = now;
    
    const bullet = this.add.rectangle(
      this.player.x, this.player.y - 20,
      4, 15, 0x00ffff
    );
    this.bullets.add(bullet);
  }

  private spawnEnemy(): void {
    const { width } = this.cameras.main;
    const x = Math.random() * (width - 60) + 30;
    
    // Different enemy types based on level
    const isFast = Math.random() < 0.2 + this.level * 0.05;
    const isShooter = Math.random() < 0.1 + this.level * 0.03;
    
    const enemy = this.add.circle(x, -30, isFast ? 15 : 20, isShooter ? 0xff0000 : 0xff6600);
    enemy.setData('type', isShooter ? 'shooter' : (isFast ? 'fast' : 'basic'));
    enemy.setData('speed', isFast ? 4 : 2 + this.level * 0.3);
    
    this.enemies.add(enemy);
  }

  private spawnPowerup(x: number, y: number): void {
    if (Math.random() > 0.2) return; // 20% chance
    
    const types = ['rapid', 'shield', 'life'];
    const type = Phaser.Math.RND.pick(types);
    const colors: Record<string, number> = {
      rapid: 0xff8800,
      shield: 0x00aaff,
      life: 0xff0000
    };
    
    const powerup = this.add.circle(x, y, 12, colors[type]);
    powerup.setData('type', type);
    this.powerups.add(powerup);
  }

  private createExplosion(x: number, y: number, color: number = 0xff8800): void {
    for (let i = 0; i < 10; i++) {
      const particle = this.add.circle(x, y, Math.random() * 4 + 2, color);
      this.particles.add(particle);
      
      const angle = Math.random() * Math.PI * 2;
      const speed = Math.random() * 100 + 50;
      
      this.tweens.add({
        targets: particle,
        x: x + Math.cos(angle) * speed,
        y: y + Math.sin(angle) * speed,
        alpha: 0,
        scale: 0,
        duration: 500,
        onComplete: () => particle.destroy()
      });
    }
  }

  private checkCollisions(): void {
    // Bullets vs Enemies
    this.bullets.getChildren().forEach((bullet: any) => {
      this.enemies.getChildren().forEach((enemy: any) => {
        if (Phaser.Geom.Intersects.RectangleToRectangle(
          bullet.getBounds(),
          enemy.getBounds()
        )) {
          this.createExplosion(enemy.x, enemy.y);
          this.spawnPowerup(enemy.x, enemy.y);
          
          bullet.destroy();
          enemy.destroy();
          
          this.score += enemy.getData('type') === 'shooter' ? 150 : 100;
          this.scoreText.setText(\`Score: \${this.score}\`);
          
          // Level up
          if (this.score >= this.level * 1000) {
            this.level++;
            this.levelText.setText(\`Level: \${this.level}\`);
          }
        }
      });
    });
    
    // Enemies vs Player
    if (!this.shield) {
      this.enemies.getChildren().forEach((enemy: any) => {
        if (Phaser.Geom.Intersects.RectangleToRectangle(
          this.player.getBounds(),
          enemy.getBounds()
        )) {
          this.createExplosion(enemy.x, enemy.y);
          enemy.destroy();
          this.loseLife();
        }
      });
    }
    
    // Powerups vs Player
    this.powerups.getChildren().forEach((powerup: any) => {
      if (Phaser.Geom.Intersects.RectangleToRectangle(
        this.player.getBounds(),
        powerup.getBounds()
      )) {
        const type = powerup.getData('type');
        powerup.destroy();
        
        switch (type) {
          case 'rapid':
            this.rapidFire = true;
            this.time.delayedCall(5000, () => { this.rapidFire = false; });
            break;
          case 'shield':
            this.shield = true;
            this.player.setFillStyle(0x00aaff);
            this.time.delayedCall(5000, () => {
              this.shield = false;
              this.player.setFillStyle(0x00ff88);
            });
            break;
          case 'life':
            this.lives = Math.min(this.lives + 1, 5);
            this.livesText.setText('❤️'.repeat(this.lives));
            break;
        }
      }
    });
  }

  private loseLife(): void {
    this.lives--;
    this.livesText.setText('❤️'.repeat(this.lives));
    
    if (this.lives <= 0) {
      this.scene.start('GameOverScene', { score: this.score });
    }
  }

  update(time: number): void {
    const body = this.player.body as Phaser.Physics.Arcade.Body;
    const { width, height } = this.cameras.main;
    
    // Player movement
    if (this.cursors.left.isDown) {
      body.setVelocityX(-300);
    } else if (this.cursors.right.isDown) {
      body.setVelocityX(300);
    } else {
      body.setVelocityX(0);
    }
    
    // Shooting
    if (this.spaceKey.isDown) {
      this.shoot();
    }
    
    // Spawn enemies
    if (time - this.lastSpawn > 1000 - this.level * 50) {
      this.lastSpawn = time;
      this.spawnEnemy();
    }
    
    // Update bullets
    this.bullets.getChildren().forEach((bullet: any) => {
      bullet.y -= 10;
      if (bullet.y < -20) bullet.destroy();
    });
    
    // Update enemies
    this.enemies.getChildren().forEach((enemy: any) => {
      const speed = enemy.getData('speed') || 2;
      enemy.y += speed;
      if (enemy.y > height + 30) enemy.destroy();
    });
    
    // Update powerups
    this.powerups.getChildren().forEach((powerup: any) => {
      powerup.y += 2;
      if (powerup.y > height + 20) powerup.destroy();
    });
    
    // Check collisions
    this.checkCollisions();
  }
}
`;

// ============================================================================
// TOP-DOWN TEMPLATE - GameScene
// ============================================================================

export const TOPDOWN_GAME_SCENE = `// ============================================================================
// 🗺️ TOP-DOWN ADVENTURE GAME SCENE
// ============================================================================
// Generated by Operator X02 Code IDE
// ============================================================================

export class GameScene extends Phaser.Scene {
  // Player
  private player!: Phaser.Physics.Arcade.Sprite;
  private cursors!: Phaser.Types.Input.Keyboard.CursorKeys;
  
  // World
  private walls!: Phaser.Physics.Arcade.StaticGroup;
  private coins!: Phaser.Physics.Arcade.Group;
  private npcs!: Phaser.Physics.Arcade.Group;
  
  // State
  private score: number = 0;
  private isInDialogue: boolean = false;
  
  // UI
  private scoreText!: Phaser.GameObjects.Text;
  private dialogueBox!: Phaser.GameObjects.Container;

  constructor() {
    super({ key: 'GameScene' });
  }

  create(): void {
    const { width, height } = this.cameras.main;

    // Grass background
    this.add.rectangle(0, 0, width, height, 0x3d8b40).setOrigin(0);
    
    // Create world
    this.createWalls();
    this.createPlayer();
    this.createCoins();
    this.createNPCs();
    
    // Collisions
    this.physics.add.collider(this.player, this.walls);
    this.physics.add.overlap(this.player, this.coins, this.collectCoin as any, undefined, this);
    this.physics.add.overlap(this.player, this.npcs, this.interactNPC as any, undefined, this);
    
    // Input
    this.cursors = this.input.keyboard!.createCursorKeys();
    this.input.keyboard!.on('keydown-E', () => this.tryInteract());
    
    // UI
    this.createUI();

    console.log('🎮 Top-Down GameScene started!');
  }

  private createWalls(): void {
    const { width, height } = this.cameras.main;
    
    this.walls = this.physics.add.staticGroup();
    
    // Border walls
    this.addWall(width / 2, 15, width, 30);
    this.addWall(width / 2, height - 15, width, 30);
    this.addWall(15, height / 2, 30, height);
    this.addWall(width - 15, height / 2, 30, height);
    
    // Interior walls (house/building)
    this.addWall(200, 150, 150, 100);
    this.addWall(500, 300, 100, 150);
    this.addWall(350, 450, 200, 30);
  }

  private addWall(x: number, y: number, w: number, h: number): void {
    const wall = this.add.rectangle(x, y, w, h, 0x5c4033);
    this.walls.add(wall);
  }

  private createPlayer(): void {
    const { height } = this.cameras.main;
    
    // Create player texture
    const graphics = this.add.graphics();
    graphics.fillStyle(0x00ff88);
    graphics.fillRect(0, 0, 28, 28);
    graphics.fillStyle(0x008844);
    graphics.fillRect(8, 4, 12, 8); // Face area
    graphics.generateTexture('player', 28, 28);
    graphics.destroy();
    
    this.player = this.physics.add.sprite(100, height - 100, 'player');
    this.player.setCollideWorldBounds(true);
  }

  private createCoins(): void {
    this.coins = this.physics.add.group();
    
    const positions = [
      { x: 150, y: 300 }, { x: 400, y: 150 },
      { x: 600, y: 200 }, { x: 200, y: 500 },
      { x: 650, y: 450 }, { x: 400, y: 400 }
    ];
    
    positions.forEach(pos => {
      const coin = this.add.circle(pos.x, pos.y, 10, 0xffd700);
      this.coins.add(coin);
    });
  }

  private createNPCs(): void {
    this.npcs = this.physics.add.group();
    
    const npcData = [
      { x: 350, y: 200, color: 0x4dabf7, dialogue: 'Hello adventurer! Collect all the coins!' },
      { x: 550, y: 500, color: 0xff6b6b, dialogue: 'Watch out for the walls!' }
    ];
    
    npcData.forEach(data => {
      const npc = this.add.rectangle(data.x, data.y, 30, 30, data.color);
      npc.setData('dialogue', data.dialogue);
      this.npcs.add(npc);
      (npc.body as Phaser.Physics.Arcade.Body).setImmovable(true);
    });
  }

  private createUI(): void {
    this.scoreText = this.add.text(16, 16, 'Coins: 0', {
      font: 'bold 24px Arial',
      color: '#ffffff',
      backgroundColor: '#00000088',
      padding: { x: 10, y: 5 }
    }).setScrollFactor(0);
    
    // Dialogue box (hidden initially)
    this.dialogueBox = this.add.container(400, 500);
    const bg = this.add.rectangle(0, 0, 600, 100, 0x000000, 0.8);
    const text = this.add.text(0, 0, '', {
      font: '18px Arial',
      color: '#ffffff',
      wordWrap: { width: 560 }
    }).setOrigin(0.5);
    const hint = this.add.text(270, 35, '[Press E to close]', {
      font: '12px Arial',
      color: '#888888'
    }).setOrigin(1, 0.5);
    
    this.dialogueBox.add([bg, text, hint]);
    this.dialogueBox.setVisible(false);
    this.dialogueBox.setScrollFactor(0);
  }

  private collectCoin(player: any, coin: any): void {
    coin.destroy();
    this.score++;
    this.scoreText.setText(\`Coins: \${this.score}\`);
    
    if (this.coins.countActive() === 0) {
      this.createCoins();
    }
  }

  private interactNPC(player: any, npc: any): void {
    // Just register that we're near an NPC
    npc.setData('nearby', true);
  }

  private tryInteract(): void {
    if (this.isInDialogue) {
      this.closeDialogue();
      return;
    }
    
    // Find nearby NPC
    this.npcs.getChildren().forEach((npc: any) => {
      const dist = Phaser.Math.Distance.Between(
        this.player.x, this.player.y,
        npc.x, npc.y
      );
      
      if (dist < 50) {
        this.showDialogue(npc.getData('dialogue'));
      }
    });
  }

  private showDialogue(text: string): void {
    this.isInDialogue = true;
    const textObj = this.dialogueBox.getAt(1) as Phaser.GameObjects.Text;
    textObj.setText(text);
    this.dialogueBox.setVisible(true);
  }

  private closeDialogue(): void {
    this.isInDialogue = false;
    this.dialogueBox.setVisible(false);
  }

  update(): void {
    if (this.isInDialogue) return;
    
    const body = this.player.body as Phaser.Physics.Arcade.Body;
    const speed = 160;
    
    body.setVelocity(0);
    
    if (this.cursors.left.isDown) {
      body.setVelocityX(-speed);
    } else if (this.cursors.right.isDown) {
      body.setVelocityX(speed);
    }
    
    if (this.cursors.up.isDown) {
      body.setVelocityY(-speed);
    } else if (this.cursors.down.isDown) {
      body.setVelocityY(speed);
    }
    
    // Normalize diagonal movement
    if (body.velocity.x !== 0 && body.velocity.y !== 0) {
      body.velocity.normalize().scale(speed);
    }
  }
}
`;

// ============================================================================
// EXPORT ALL TEMPLATES
// ============================================================================

export const GAME_SCENE_TEMPLATES = {
  platformer: PLATFORMER_GAME_SCENE,
  shooter: SHOOTER_GAME_SCENE,
  topdown: TOPDOWN_GAME_SCENE
};

console.log('[GameTemplates] Module loaded');
